CREATE SEQUENCE IF NOT EXISTS SYS_VECTOR_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS SYS_VECTOR_COLUMNS_ (
    COLUMN_ID BIGINT NOT NULL,
    TENANT_ID VARCHAR(64) NOT NULL,
    SCHEMA_NAME VARCHAR(128) NOT NULL,
    TABLE_NAME VARCHAR(128) NOT NULL,
    COLUMN_NAME VARCHAR(128) NOT NULL,
    PK_COLUMN_NAME VARCHAR(128) NOT NULL,
    VECTOR_DIM INTEGER NOT NULL,
    METRIC_TYPE VARCHAR(16) NOT NULL,
    VECTOR_ENCODING VARCHAR(32) NOT NULL,
    POINT_ID_MODE VARCHAR(16) NOT NULL,
    DELETE_POLICY VARCHAR(16) NOT NULL,
    STATUS VARCHAR(16) NOT NULL,
    SYNC_MODE VARCHAR(32) NOT NULL,
    DEFINITION_HASH VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    REMARK VARCHAR(1024),
    PRIMARY KEY (COLUMN_ID),
    CONSTRAINT UQ_SYS_VECTOR_COLUMNS_01 UNIQUE (TENANT_ID, SCHEMA_NAME, TABLE_NAME, COLUMN_NAME),
    CONSTRAINT CK_SYS_VECTOR_COLUMNS_01 CHECK (STATUS IN ('BUILDING', 'ACTIVE', 'FAILED', 'DISABLED')),
    CONSTRAINT CK_SYS_VECTOR_COLUMNS_02 CHECK (SYNC_MODE IN ('FULL_AND_INCREMENTAL', 'FULL_ONLY'))
);

CREATE TABLE IF NOT EXISTS SYS_VECTOR_COLLECTIONS_ (
    COLLECTION_ID BIGINT NOT NULL,
    COLUMN_ID BIGINT NOT NULL,
    ENGINE_TYPE VARCHAR(16) NOT NULL,
    NAMESPACE_NAME VARCHAR(128) NOT NULL,
    COLLECTION_NAME VARCHAR(256) NOT NULL,
    ALIAS_NAME VARCHAR(256),
    COLLECTION_VERSION VARCHAR(64) NOT NULL,
    SERVING_STATE VARCHAR(16) NOT NULL,
    COLLECTION_STATUS VARCHAR(16) NOT NULL,
    QDRANT_VECTOR_NAME VARCHAR(128) NOT NULL,
    QDRANT_ID_TYPE VARCHAR(16) NOT NULL,
    DISTANCE_METRIC VARCHAR(16) NOT NULL,
    VECTOR_DIM INTEGER NOT NULL,
    SHARD_NUMBER INTEGER,
    REPLICATION_FACTOR INTEGER,
    WRITE_CONSISTENCY_FACTOR INTEGER,
    ON_DISK_PAYLOAD CHAR(1) NOT NULL,
    HNSW_CONFIG_JSON VARCHAR(4000),
    QUANTIZATION_CONFIG_JSON VARCHAR(4000),
    COLLECTION_CONFIG_JSON VARCHAR(4000),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (COLLECTION_ID),
    CONSTRAINT UQ_SYS_VECTOR_COLLECTIONS_01 UNIQUE (ENGINE_TYPE, NAMESPACE_NAME, COLLECTION_NAME),
    CONSTRAINT UQ_SYS_VECTOR_COLLECTIONS_02 UNIQUE (COLUMN_ID, COLLECTION_VERSION),
    CONSTRAINT FK_SYS_VECTOR_COLLECTIONS_01 FOREIGN KEY (COLUMN_ID) REFERENCES SYS_VECTOR_COLUMNS_ (COLUMN_ID),
    CONSTRAINT CK_SYS_VECTOR_COLLECTIONS_01 CHECK (SERVING_STATE IN ('BUILDING', 'ACTIVE', 'DEPRECATED')),
    CONSTRAINT CK_SYS_VECTOR_COLLECTIONS_02 CHECK (COLLECTION_STATUS IN ('CREATING', 'READY', 'FAILED', 'DROPPED')),
    CONSTRAINT CK_SYS_VECTOR_COLLECTIONS_03 CHECK (
        VECTOR_DIM > 0
        AND (SHARD_NUMBER IS NULL OR SHARD_NUMBER > 0)
        AND (REPLICATION_FACTOR IS NULL OR REPLICATION_FACTOR > 0)
        AND (WRITE_CONSISTENCY_FACTOR IS NULL OR WRITE_CONSISTENCY_FACTOR > 0)
    ),
    CONSTRAINT CK_SYS_VECTOR_COLLECTIONS_04 CHECK (
        (SERVING_STATE = 'BUILDING' AND COLLECTION_STATUS IN ('CREATING', 'FAILED'))
        OR (SERVING_STATE = 'ACTIVE' AND COLLECTION_STATUS = 'READY')
        OR (SERVING_STATE = 'DEPRECATED' AND COLLECTION_STATUS IN ('READY', 'DROPPED'))
    )
);

CREATE TABLE IF NOT EXISTS SYS_VECTOR_INDEXES_ (
    INDEX_ID BIGINT NOT NULL,
    COLUMN_ID BIGINT NOT NULL,
    COLLECTION_ID BIGINT,
    PROFILE_NAME VARCHAR(128) NOT NULL,
    INDEX_TYPE VARCHAR(32) NOT NULL,
    METRIC_TYPE VARCHAR(16) NOT NULL,
    INDEX_PARAMS_JSON VARCHAR(4000),
    SEARCH_PARAMS_JSON VARCHAR(4000),
    PAYLOAD_INDEX_JSON VARCHAR(4000),
    IS_DEFAULT CHAR(1) NOT NULL,
    SERVING_STATE VARCHAR(16) NOT NULL,
    INDEX_STATUS VARCHAR(16) NOT NULL,
    BUILD_VERSION VARCHAR(64),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (INDEX_ID),
    CONSTRAINT UQ_SYS_VECTOR_INDEXES_01 UNIQUE (COLUMN_ID, PROFILE_NAME),
    CONSTRAINT FK_SYS_VECTOR_INDEXES_01 FOREIGN KEY (COLUMN_ID) REFERENCES SYS_VECTOR_COLUMNS_ (COLUMN_ID),
    CONSTRAINT FK_SYS_VECTOR_INDEXES_02 FOREIGN KEY (COLLECTION_ID) REFERENCES SYS_VECTOR_COLLECTIONS_ (COLLECTION_ID),
    CONSTRAINT CK_SYS_VECTOR_INDEXES_01 CHECK (IS_DEFAULT IN ('Y', 'N')),
    CONSTRAINT CK_SYS_VECTOR_INDEXES_02 CHECK (SERVING_STATE IN ('ONLINE', 'OFFLINE', 'CANARY')),
    CONSTRAINT CK_SYS_VECTOR_INDEXES_03 CHECK (INDEX_STATUS IN ('CREATING', 'READY', 'FAILED', 'REBUILDING')),
    CONSTRAINT CK_SYS_VECTOR_INDEXES_04 CHECK (COLLECTION_ID IS NULL OR COLLECTION_ID > 0),
    CONSTRAINT CK_SYS_VECTOR_INDEXES_05 CHECK (
        (SERVING_STATE = 'ONLINE' AND INDEX_STATUS = 'READY')
        OR (SERVING_STATE = 'OFFLINE' AND INDEX_STATUS IN ('CREATING', 'READY', 'FAILED', 'REBUILDING'))
        OR (SERVING_STATE = 'CANARY' AND INDEX_STATUS = 'READY')
    )
);

CREATE TABLE IF NOT EXISTS SYS_VECTOR_PAYLOAD_FIELDS_ (
    FIELD_ID BIGINT NOT NULL,
    COLUMN_ID BIGINT NOT NULL,
    SOURCE_COLUMN_NAME VARCHAR(128) NOT NULL,
    PAYLOAD_KEY VARCHAR(128) NOT NULL,
    FIELD_TYPE VARCHAR(64) NOT NULL,
    IS_FILTERABLE CHAR(1) NOT NULL,
    IS_RETURNABLE CHAR(1) NOT NULL,
    IS_INDEXED CHAR(1) NOT NULL,
    SYNC_ENABLED CHAR(1) NOT NULL,
    FIELD_STATUS VARCHAR(16) NOT NULL,
    INDEX_PARAMS_JSON VARCHAR(2000),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (FIELD_ID),
    CONSTRAINT UQ_SYS_VECTOR_PAYLOAD_FIELDS_01 UNIQUE (COLUMN_ID, PAYLOAD_KEY),
    CONSTRAINT FK_SYS_VECTOR_PAYLOAD_FIELDS_01 FOREIGN KEY (COLUMN_ID) REFERENCES SYS_VECTOR_COLUMNS_ (COLUMN_ID),
    CONSTRAINT CK_SYS_VECTOR_PAYLOAD_FIELDS_01 CHECK (IS_FILTERABLE IN ('Y', 'N')),
    CONSTRAINT CK_SYS_VECTOR_PAYLOAD_FIELDS_02 CHECK (IS_RETURNABLE IN ('Y', 'N')),
    CONSTRAINT CK_SYS_VECTOR_PAYLOAD_FIELDS_03 CHECK (IS_INDEXED IN ('Y', 'N')),
    CONSTRAINT CK_SYS_VECTOR_PAYLOAD_FIELDS_04 CHECK (SYNC_ENABLED IN ('Y', 'N')),
    CONSTRAINT CK_SYS_VECTOR_PAYLOAD_FIELDS_05 CHECK (FIELD_STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE IF NOT EXISTS SYS_VECTOR_OUTBOX_EVENTS_ (
    EVENT_ID BIGINT NOT NULL,
    TENANT_ID VARCHAR(64) NOT NULL,
    COLUMN_ID BIGINT NOT NULL,
    EVENT_KEY VARCHAR(768) NOT NULL,
    ACTIVE_KEY VARCHAR(768),
    EVENT_TYPE VARCHAR(16) NOT NULL,
    SOURCE_OP VARCHAR(16) NOT NULL,
    EVENT_STATUS VARCHAR(16) NOT NULL,
    SOURCE_PK VARCHAR(512) NOT NULL,
    POINT_ID VARCHAR(128) NOT NULL,
    PK_VALUE_TYPE VARCHAR(16) NOT NULL,
    DEDUPE_KEY VARCHAR(1024) NOT NULL,
    SOURCE_VERSION BIGINT NOT NULL,
    NEEDS_RESYNC CHAR(1) NOT NULL,
    RETRY_COUNT INTEGER NOT NULL,
    NEXT_RETRY_AT TIMESTAMP,
    NEXT_RETRY_AT_EPOCH_MS BIGINT,
    LOCKED_BY VARCHAR(128),
    LOCKED_AT TIMESTAMP,
    LOCKED_AT_EPOCH_MS BIGINT,
    CLAIM_TOKEN VARCHAR(64),
    FINISHED_AT TIMESTAMP,
    FINISHED_AT_EPOCH_MS BIGINT,
    ERROR_CODE VARCHAR(64),
    ERROR_MESSAGE VARCHAR(2048),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (EVENT_ID),
    CONSTRAINT UQ_SYS_VECTOR_OUTBOX_EVENTS_01 UNIQUE (DEDUPE_KEY),
    CONSTRAINT UQ_SYS_VECTOR_OUTBOX_EVENTS_02 UNIQUE (ACTIVE_KEY),
    CONSTRAINT FK_SYS_VECTOR_OUTBOX_EVENTS_01 FOREIGN KEY (COLUMN_ID) REFERENCES SYS_VECTOR_COLUMNS_ (COLUMN_ID),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_01 CHECK (EVENT_TYPE IN ('UPSERT', 'DELETE')),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_02 CHECK (SOURCE_OP IN ('INSERT', 'UPDATE', 'DELETE')),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_03 CHECK (EVENT_STATUS IN ('PENDING', 'PROCESSING', 'DONE', 'RETRYING', 'DEAD')),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_04 CHECK (PK_VALUE_TYPE IN ('NUMBER', 'STRING')),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_05 CHECK (RETRY_COUNT >= 0),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_06 CHECK (
        (NEXT_RETRY_AT IS NULL AND NEXT_RETRY_AT_EPOCH_MS IS NULL)
        OR
        (NEXT_RETRY_AT IS NOT NULL AND NEXT_RETRY_AT_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_07 CHECK (
        (LOCKED_AT IS NULL AND LOCKED_AT_EPOCH_MS IS NULL)
        OR
        (LOCKED_AT IS NOT NULL AND LOCKED_AT_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_08 CHECK (
        (FINISHED_AT IS NULL AND FINISHED_AT_EPOCH_MS IS NULL)
        OR
        (FINISHED_AT IS NOT NULL AND FINISHED_AT_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_09 CHECK (SOURCE_VERSION > 0),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_10 CHECK (NEEDS_RESYNC IN ('Y', 'N')),
    CONSTRAINT CK_SYS_VECTOR_OUTBOX_EVENTS_11 CHECK (
        (EVENT_STATUS = 'DONE' AND ACTIVE_KEY IS NULL)
        OR
        (EVENT_STATUS <> 'DONE' AND ACTIVE_KEY IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS SYS_VECTOR_SOURCE_VERSIONS_ (
    EVENT_KEY VARCHAR(768) NOT NULL,
    TENANT_ID VARCHAR(64) NOT NULL,
    COLUMN_ID BIGINT NOT NULL,
    SOURCE_PK VARCHAR(512) NOT NULL,
    CURRENT_VERSION BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (EVENT_KEY),
    CONSTRAINT FK_SYS_VECTOR_SOURCE_VERSIONS_01 FOREIGN KEY (COLUMN_ID) REFERENCES SYS_VECTOR_COLUMNS_ (COLUMN_ID),
    CONSTRAINT CK_SYS_VECTOR_SOURCE_VERSIONS_01 CHECK (CURRENT_VERSION > 0)
);

CREATE TABLE IF NOT EXISTS SYS_VECTOR_SYNC_JOBS_ (
    JOB_ID BIGINT NOT NULL,
    COLUMN_ID BIGINT NOT NULL,
    COLLECTION_ID BIGINT,
    INDEX_ID BIGINT,
    JOB_TYPE VARCHAR(16) NOT NULL,
    JOB_STATUS VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(16) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(128),
    SNAPSHOT_ID VARCHAR(128),
    SOURCE_CURSOR VARCHAR(512),
    START_PK VARCHAR(512),
    END_PK VARCHAR(512),
    WORKER_ID VARCHAR(128),
    ATTEMPT_NO INTEGER NOT NULL,
    RETRY_COUNT INTEGER NOT NULL,
    ERROR_CODE VARCHAR(64),
    ERROR_MESSAGE VARCHAR(2048),
    HEARTBEAT_AT TIMESTAMP,
    HEARTBEAT_AT_EPOCH_MS BIGINT,
    STARTED_AT TIMESTAMP,
    STARTED_AT_EPOCH_MS BIGINT,
    FINISHED_AT TIMESTAMP,
    FINISHED_AT_EPOCH_MS BIGINT,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (JOB_ID),
    CONSTRAINT UQ_SYS_VECTOR_SYNC_JOBS_01 UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_SYS_VECTOR_SYNC_JOBS_01 FOREIGN KEY (COLUMN_ID) REFERENCES SYS_VECTOR_COLUMNS_ (COLUMN_ID),
    CONSTRAINT FK_SYS_VECTOR_SYNC_JOBS_02 FOREIGN KEY (COLLECTION_ID) REFERENCES SYS_VECTOR_COLLECTIONS_ (COLLECTION_ID),
    CONSTRAINT FK_SYS_VECTOR_SYNC_JOBS_03 FOREIGN KEY (INDEX_ID) REFERENCES SYS_VECTOR_INDEXES_ (INDEX_ID),
    CONSTRAINT CK_SYS_VECTOR_SYNC_JOBS_01 CHECK (JOB_STATUS IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PAUSED', 'CANCELED')),
    CONSTRAINT CK_SYS_VECTOR_SYNC_JOBS_02 CHECK (
        (HEARTBEAT_AT IS NULL AND HEARTBEAT_AT_EPOCH_MS IS NULL)
        OR
        (HEARTBEAT_AT IS NOT NULL AND HEARTBEAT_AT_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_JOBS_03 CHECK (
        (STARTED_AT IS NULL AND STARTED_AT_EPOCH_MS IS NULL)
        OR
        (STARTED_AT IS NOT NULL AND STARTED_AT_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_JOBS_04 CHECK (
        (FINISHED_AT IS NULL AND FINISHED_AT_EPOCH_MS IS NULL)
        OR
        (FINISHED_AT IS NOT NULL AND FINISHED_AT_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_JOBS_05 CHECK (
        (JOB_STATUS = 'PENDING' AND STARTED_AT IS NULL AND STARTED_AT_EPOCH_MS IS NULL AND FINISHED_AT IS NULL AND FINISHED_AT_EPOCH_MS IS NULL)
        OR
        (JOB_STATUS IN ('RUNNING', 'PAUSED') AND STARTED_AT IS NOT NULL AND STARTED_AT_EPOCH_MS IS NOT NULL AND FINISHED_AT IS NULL AND FINISHED_AT_EPOCH_MS IS NULL)
        OR
        (JOB_STATUS IN ('SUCCESS', 'FAILED', 'CANCELED') AND STARTED_AT IS NOT NULL AND STARTED_AT_EPOCH_MS IS NOT NULL AND FINISHED_AT IS NOT NULL AND FINISHED_AT_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_JOBS_06 CHECK (
        (JOB_STATUS = 'RUNNING' AND HEARTBEAT_AT IS NOT NULL AND HEARTBEAT_AT_EPOCH_MS IS NOT NULL)
        OR
        (JOB_STATUS <> 'RUNNING' AND HEARTBEAT_AT IS NULL AND HEARTBEAT_AT_EPOCH_MS IS NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_JOBS_07 CHECK (
        (COLLECTION_ID IS NULL OR COLLECTION_ID > 0)
        AND (INDEX_ID IS NULL OR INDEX_ID > 0)
        AND ATTEMPT_NO >= 0
        AND RETRY_COUNT >= 0
    )
);

CREATE TABLE IF NOT EXISTS SYS_VECTOR_SYNC_PROGRESS_ (
    PROGRESS_ID BIGINT NOT NULL,
    JOB_ID BIGINT NOT NULL,
    COLUMN_ID BIGINT NOT NULL,
    PARTITION_ID VARCHAR(64) NOT NULL,
    LAST_PK VARCHAR(512),
    LAST_EVENT_TIME TIMESTAMP,
    LAST_EVENT_TIME_EPOCH_MS BIGINT,
    LAST_EVENT_ID VARCHAR(128),
    PROCESSED_ROWS BIGINT NOT NULL,
    SUCCESS_ROWS BIGINT NOT NULL,
    FAILED_ROWS BIGINT NOT NULL,
    LAST_BATCH_TIME TIMESTAMP,
    LAST_BATCH_TIME_EPOCH_MS BIGINT,
    PROGRESS_STATUS VARCHAR(16) NOT NULL,
    CHECKPOINT_DATA VARCHAR(2000),
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (PROGRESS_ID),
    CONSTRAINT UQ_SYS_VECTOR_SYNC_PROGRESS_01 UNIQUE (JOB_ID, PARTITION_ID),
    CONSTRAINT FK_SYS_VECTOR_SYNC_PROGRESS_01 FOREIGN KEY (JOB_ID) REFERENCES SYS_VECTOR_SYNC_JOBS_ (JOB_ID),
    CONSTRAINT FK_SYS_VECTOR_SYNC_PROGRESS_02 FOREIGN KEY (COLUMN_ID) REFERENCES SYS_VECTOR_COLUMNS_ (COLUMN_ID),
    CONSTRAINT CK_SYS_VECTOR_SYNC_PROGRESS_01 CHECK (PROGRESS_STATUS IN ('RUNNING', 'STALLED', 'DONE', 'FAILED')),
    CONSTRAINT CK_SYS_VECTOR_SYNC_PROGRESS_02 CHECK (
        (LAST_EVENT_TIME IS NULL AND LAST_EVENT_TIME_EPOCH_MS IS NULL)
        OR
        (LAST_EVENT_TIME IS NOT NULL AND LAST_EVENT_TIME_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_PROGRESS_03 CHECK (
        (LAST_BATCH_TIME IS NULL AND LAST_BATCH_TIME_EPOCH_MS IS NULL)
        OR
        (LAST_BATCH_TIME IS NOT NULL AND LAST_BATCH_TIME_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_PROGRESS_04 CHECK (
        PROCESSED_ROWS >= 0
        AND SUCCESS_ROWS >= 0
        AND FAILED_ROWS >= 0
    )
);

CREATE TABLE IF NOT EXISTS SYS_VECTOR_SYNC_ERRORS_ (
    ERROR_ID BIGINT NOT NULL,
    JOB_ID BIGINT NOT NULL,
    COLUMN_ID BIGINT NOT NULL,
    PARTITION_ID VARCHAR(64),
    SOURCE_PK VARCHAR(512) NOT NULL,
    OP_TYPE VARCHAR(16) NOT NULL,
    ERROR_STAGE VARCHAR(32) NOT NULL,
    ERROR_CODE VARCHAR(64) NOT NULL,
    ERROR_MESSAGE VARCHAR(2048) NOT NULL,
    PAYLOAD_SNAPSHOT VARCHAR(2000),
    DEDUPE_KEY VARCHAR(256) NOT NULL,
    FIRST_SEEN_AT TIMESTAMP NOT NULL,
    LAST_SEEN_AT TIMESTAMP NOT NULL,
    LAST_SEEN_AT_EPOCH_MS BIGINT NOT NULL,
    RETRY_COUNT INTEGER NOT NULL,
    NEXT_RETRY_AT TIMESTAMP,
    NEXT_RETRY_AT_EPOCH_MS BIGINT,
    ERROR_STATUS VARCHAR(16) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ERROR_ID),
    CONSTRAINT UQ_SYS_VECTOR_SYNC_ERRORS_01 UNIQUE (DEDUPE_KEY),
    CONSTRAINT FK_SYS_VECTOR_SYNC_ERRORS_01 FOREIGN KEY (JOB_ID) REFERENCES SYS_VECTOR_SYNC_JOBS_ (JOB_ID),
    CONSTRAINT FK_SYS_VECTOR_SYNC_ERRORS_02 FOREIGN KEY (COLUMN_ID) REFERENCES SYS_VECTOR_COLUMNS_ (COLUMN_ID),
    CONSTRAINT CK_SYS_VECTOR_SYNC_ERRORS_01 CHECK (ERROR_STATUS IN ('OPEN', 'RETRYING', 'RESOLVED', 'DEAD')),
    CONSTRAINT CK_SYS_VECTOR_SYNC_ERRORS_02 CHECK (
        (NEXT_RETRY_AT IS NULL AND NEXT_RETRY_AT_EPOCH_MS IS NULL)
        OR
        (NEXT_RETRY_AT IS NOT NULL AND NEXT_RETRY_AT_EPOCH_MS IS NOT NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_ERRORS_03 CHECK (
        ERROR_STATUS = 'RETRYING'
        OR
        (NEXT_RETRY_AT IS NULL AND NEXT_RETRY_AT_EPOCH_MS IS NULL)
    ),
    CONSTRAINT CK_SYS_VECTOR_SYNC_ERRORS_04 CHECK (
        RETRY_COUNT >= 0
    )
);

CREATE INDEX IF NOT EXISTS IX_SYS_VECTOR_SYNC_JOBS_01
    ON SYS_VECTOR_SYNC_JOBS_ (JOB_STATUS, HEARTBEAT_AT_EPOCH_MS);

CREATE INDEX IF NOT EXISTS IX_SYS_VECTOR_SYNC_ERRORS_01
    ON SYS_VECTOR_SYNC_ERRORS_ (ERROR_STATUS, NEXT_RETRY_AT_EPOCH_MS);

CREATE INDEX IF NOT EXISTS IX_SYS_VECTOR_OUTBOX_EVENTS_01
    ON SYS_VECTOR_OUTBOX_EVENTS_ (EVENT_STATUS, NEXT_RETRY_AT_EPOCH_MS);

CREATE INDEX IF NOT EXISTS IX_SYS_VECTOR_OUTBOX_EVENTS_02
    ON SYS_VECTOR_OUTBOX_EVENTS_ (EVENT_STATUS, LOCKED_AT_EPOCH_MS);

CREATE INDEX IF NOT EXISTS IX_SYS_VECTOR_OUTBOX_EVENTS_03
    ON SYS_VECTOR_OUTBOX_EVENTS_ (EVENT_KEY);

CREATE INDEX IF NOT EXISTS IX_SYS_VECTOR_SOURCE_VERSIONS_01
    ON SYS_VECTOR_SOURCE_VERSIONS_ (COLUMN_ID, SOURCE_PK);
